apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: content-library-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/MY_GCP_PROJECT/secrets/SECRET_ENV_FILE/versions/latest"
        path: ".env"
