apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: content-library-dev


patchesStrategicMerge:
- ./serviceaccount.yaml
- ./ingress.yaml
- ./deployment.yaml
resources:
- ../../base
images:
- name: gcr.io/adhoc-dev-service-platform/content-library
  newTag: e0852fb04fe2db22fbc77928f76728acb0630dd9
