apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: content-library-dev


patchesStrategicMerge:
- ./serviceaccount.yaml
- ./ingress.yaml
- ./deployment.yaml
resources:
- ../../base
images:
- name: gcr.io/adhoc-dev-service-platform/content-library
  newTag: 22346a2c90091dd378137c4c92a8e95ba25a0f20
