apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-library
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: content-library
    spec:
      containers:
      - name: content-library
        image: gcr.io/adhoc-dev-service-platform/content-library:latest
        env:
          - name: "GCP_PROJECT_ID"
            value: "content-library-viewer"
        nodeSelector: {}
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 25
                preference:
                  matchExpressions:
                    - key: platform.adhoc.dev/cost-type
                      operator: In
                      values:
                        - on-demand
              - weight: 30
                preference:
                  matchExpressions:
                    - key: platform.adhoc.dev/cost-type
                      operator: In
                      values:
                        - spot
