apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: content-library-prod

bases:
  - ../../base

patches:
  - ./serviceaccount.yaml
  - ./deployment.yaml
  - ./secretproviderclass.yaml
