name: Deploy GAE application to Dev
on:
  push:
    # branches:
    #   - main
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
      NODE_ENV: development
    steps:
      - name: Checking Repository
        uses: actions/checkout@v2

      - name: Setup cloud SDK with Dev project info
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: '${{ secrets.DEV_PROJECT_ID }}'
          service_account_key: '${{ secrets.DEV_GCP_SA_KEY }}'
      
      - name: Generate .env file
        run: |
          touch .env
          echo "NODE_ENV=${{ env.NODE_ENV }} >> .env"
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env"
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env"
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }} >> .env"
          echo "GOOGLE_APPLICATION_JSON=${{ secrets.GOOGLE_APPLICATION_JSON }} >> .env"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} .env"
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} >> .env"
          echo "APPROVED_DOMAINS=${{ secrets.APPROVED_DOMAINS }} >> .env"
          echo "DRIVE_TYPE=${{ secrets.DRIVE_TYPE }} >> .env"
          echo "DRIVE_ID=${{ secrets.DRIVE_ID }} >> .env"

      - name: Deploy to dev GAE project
        run: 'gcloud app deploy app.yaml --quiet --version ${{ env.TAG }}'
