name: Deploy GAE application to Dev
on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: Checking Repository
        uses: actions/checkout@v2

      - name: Setup cloud SDK with Dev project info
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: '${{ secrets.DEV_PROJECT_ID }}'
          service_account_key: '${{ secrets.DEV_GCP_SA_KEY }}'

      - name: Deploy to dev GAE project
        run: 'gcloud app deploy app.yaml --version ${{ env.TAG }}'
