name: Deploy Content Library to Google App Engine (GAE)
on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    strategy:
      max-parallel: 1
      matrix:
        environment: [dev, prod]
        include:
          - environment: dev
            PROJECT_ID: DEV_PROJECT_ID
            GCP_SA_KEY: DEV_GCP_SA_KEY
          - environment: prod
            PROJECT_ID: PROD_PROJECT_ID
            GCP_SA_KEY: PROD_GCP_SA_KEY
    steps:
      - name: Checking Repository
        uses: actions/checkout@v2

      - name: Setup cloud SDK with Dev project info
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: '${{ secrets[matrix.PROJECT_ID] }}'
          service_account_key: '${{ secrets[matrix.GCP_SA_KEY] }}'

      - name: Deploy to dev GAE project
        run: 'gcloud app deploy app.yaml --quiet --version ${{ env.TAG }}'
