# This is a basic workflow to help you get started with Actions

name: Library PR CI Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      # This is where the application is initially being built
      - name: 'Set up Node v16'
        uses: actions/setup-node@v3
        with: 
           node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build a production app
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      # This is where the application is initially being built
      - name: 'Set up Node v16'
        uses: actions/setup-node@v3
        with: 
           node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  unit-tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      # This is where the application is initially being built
      - name: 'Set up Node v16'
        uses: actions/setup-node@v3
        with: 
           node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test
