# This is a basic workflow to help you get started with Actions

name: Library PR CI Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - name: Checking Repository
        uses: actions/checkout@v2

      # This is where the application is initially being built
      - name: 'Building Application'
        uses: actions/setup-node@v1
        with: 
           node-version: '16.x'
      - run: npm ci
      - run: npm run build
